### PR TITLE
Update Metadata + Screenshots of Activities- GCI task

### PR DESCRIPTION
**Pull request by mayankkuthar**

### CODE REVIEW

**Review by vipulgupta2048 — CHANGES_REQUESTED** [review]
Thanks for making a PR, good first attempt. A couple of pointers. 
- The images need to be optimized, with naming conventions as `1.png`, `2.png` 
- According to https://github.com/sugarlabs/sugar-toolkit-gtk3/blob/master/src/sugar3/bundle/__init__.py, `License` field is a compulsory tag that the activity should have. Please do add that. 
(Tip - You can use the script mentioned in the task to achieve the same. )
- Try to find more tags that you could add to the `activity.info` file.

**Comment by vipulgupta2048** [comment]
@quozl @llaske If you can further review, that would be great. Thanks.

**Comment by quozl** [comment]
Thanks.

* [x] please send the pull request to Sugarizer, as the README.md file says

> FoodChain activity is now part of Sugarizer. This repository is no longer maintain. If you want to contribute, send PR directly in Sugarizer.

* [x] please check the license; you said GPLv3+, but in Sugarizer the activity is released by the author under an Apache 2.0 license,
* [ ] please confirm that the activity still runs in Sugar before adding screenshots or metadata required by activities.sugarlabs.org; it would be a waste of time to add this if it won't be used.

**Comment by quozl** [comment]
If the activity still runs in Sugar, the license value is processed by a program, and must be exact.  Valid license abbreviations can be found in the source code of the web application activities.sugarlabs.org, see https://github.com/sugarlabs/aslo/blob/6a177c9594cb92f84d172f5c6dc8b5a1dd4da6dd/site/app/controllers/developers_controller.php#L62

**Comment by mayankkuthar** [comment]
Thanks! @quozl  I have made the updated PR on sugarizer repo as you said

**Comment by quozl** [comment]
You forgot to link it; https://github.com/llaske/sugarizer/pull/227

When will you close this pull request?  I can't.

**Pull request closed without merging**
